force-app/main/default/objects/Account/fields/FPSA_Is_Public__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Is_Public__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Company Is Public</inlineHelpText>
    <label>Is Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <defaultValue>&quot;Staged&quot;</defaultValue>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staged</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Outreach</fullName>
            </value>
            <value>
                <fullName>Engaged</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Current Customer</fullName>
            </value>
            <value>
                <fullName>Reference</fullName>
            </value>
            <value>
                <fullName>Past Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Caelius_Alignment__c.field-meta.xml
<CustomField>
    <fullName>Caelius_Alignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Who at Caelius is aligned to this contact, or the primary holder of the relationship</inlineHelpText>
    <label>Caelius Alignment</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staged</fullName>
                <default>true</default>
                <label>Staged</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Initiated TAM</fullName>
            </value>
            <value>
                <fullName>Opted In</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Advocate</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Email Bounce</fullName>
            </value>
            <value>
                <fullName>Unsubscribed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Salesforce.recordType-meta.xml
<RecordType>
    <fullName>Salesforce</fullName>
    <active>true</active>
    <description>Salesforce Employee: Sales, Alliance, Product, other</description>
    <label>Salesforce</label>
</RecordType>

force-app/main/default/classes/ContactHelperTest.cls
@isTest
public class ContactHelperTest {
	@TestSetup
	static void createTestData() {
    	Account acc = new Account();
    	acc.Name = 'Test Account';
        acc.Stage__c = 'Staged';
        acc.FPSA_Is_Public__c = false;
        insert acc;
        
        Account acc2 = new Account();
    	acc2.Name = 'Test Account 2';
        acc2.Stage__c = 'Staged';
        acc2.FPSA_Is_Public__c = false;
        insert acc2;
        
        List<Contact> testContactsList = new List<Contact>();
        Contact testAlignmentParentCon = new Contact();
        testAlignmentParentCon.RecordTypeId = Schema.sObjectType.Contact.getRecordTypeInfosByName().get('Salesforce').getRecordTypeId();
        testAlignmentParentCon.LastName = 'Test Alignment Individual';
        testAlignmentParentCon.AccountId = acc2.Id;
        insert testAlignmentParentCon;
        
        Contact testAlignmentContact = new Contact();
        testAlignmentContact.RecordTypeId = Schema.sObjectType.Contact.getRecordTypeInfosByName().get('Salesforce').getRecordTypeId();
        testAlignmentContact.LastName = 'Test Alignment Contact';
        testAlignmentContact.AccountId = acc.Id;
        testAlignmentContact.ReportsToId = testAlignmentParentCon.Id;
        insert testAlignmentContact;
            
        Contact testCon1 = new Contact();
        testCon1.RecordTypeId = Schema.sObjectType.Contact.getRecordTypeInfosByName().get('Salesforce').getRecordTypeId();
        testCon1.LastName = 'testCont1';
        testCon1.AccountId = acc.Id;
        insert testCon1;
        
        Contact testCon2 = new Contact();
        testCon2.RecordTypeId = Schema.sObjectType.Contact.getRecordTypeInfosByName().get('Salesforce').getRecordTypeId();
        testCon2.LastName = 'testCont2';
        testCon2.AccountId = acc.Id;
        testCon2.ReportsToId = testCon1.Id;
        insert testCon2;
        Contact testCon3 = new Contact();
        testCon3.RecordTypeId = Schema.sObjectType.Contact.getRecordTypeInfosByName().get('Salesforce').getRecordTypeId();
        testCon3.LastName = 'testCont3';
        testCon3.AccountId = acc.Id;
        testCon3.ReportsToId = testCon2.Id;
        
        
        insert testCon3;
	}
    
    @isTest
    static void updateChildRecordsTest() {
		List<Contact> alignmentConList = [SELECT Id FROM Contact WHERE LastName = 'Test Alignment Individual'];
        Contact parentCon = [SELECT Id FROM Contact WHERE LastName = 'testCont1'][0];
        parentCon.Caelius_Alignment__c = alignmentConList[0].Id;
        Test.startTest();
        update parentCon;
        Test.stopTest();
    } 
}