force-app/main/default/objects/Log_Table__c/Log_Table__c.object-meta.xml
<CustomObject>
    <description>For Task:
Log time Feature - Project Task

https://fusionconsultinginc.lightning.force.com/lightning/r/MPM4_BASE__Milestone1_Task__c/a0f3k00000UvEeAAAV/view</description>
    <label>Log Table</label>
    <nameField>
        <displayFormat>Log Time - {000000}</displayFormat>
        <label>Log Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_Table__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Log_Table__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>MPM4_BASE__Milestone1_Resource__c</referenceTo>
    <relationshipName>log_tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log_Table__c/fields/ResourceName__c.field-meta.xml
<CustomField>
    <fullName>ResourceName__c</fullName>
    <formula>Resource__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ResourceName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Table__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Task</label>
    <referenceTo>MPM4_BASE__Milestone1_Task__c</referenceTo>
    <relationshipName>log_tables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log_Table__c/fields/Time_Spent__c.field-meta.xml
<CustomField>
    <fullName>Time_Spent__c</fullName>
    <inlineHelpText>in Hours</inlineHelpText>
    <label>Time Spent</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Table__c/fields/Work_Description__c.field-meta.xml
<CustomField>
    <fullName>Work_Description__c</fullName>
    <description>will concatenate on timesheet level</description>
    <label>Work Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPM4_BASE__Milestone1_Resource__c/MPM4_BASE__Milestone1_Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/MPM4_BASE__Milestone1_Resource__c/fields/MPM4_BASE__User__c.field-meta.xml
<CustomField>
    <fullName>MPM4_BASE__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FPSA_LogTimeOnTaskController.cls
/*
* Controller class for lwcLogTimeOnTask and LogTimeOnTask components.
*/
public with sharing class FPSA_LogTimeOnTaskController {
    @AuraEnabled(cacheable=true)
    public static list<Log_Table__c> getLog(String taskId) {
        return [SELECT Id, Name, Time_Spent__c, Work_Description__c, Date__c ,Resource__c,ResourceName__c
                    FROM Log_Table__c 
                    WHERE Task__c = :taskId 
                    ORDER BY Date__c DESC];
    }

    @AuraEnabled()
    Public static Date insertLog(Integer a_Time_Spent, String a_Work_Description, Date a_Date, String a_taskId){
        System.debug('An a_taskId: '+a_taskId);    
        try{
            Id loggedinUserId= userInfo.getUserId(); 
            Id a_resourceId = [Select Id, Name, MPM4_BASE__User__c FROM MPM4_BASE__Milestone1_Resource__c where MPM4_BASE__User__c =: loggedinUserId].Id;
            return insLOG( a_Time_Spent, a_Work_Description,a_Date,a_taskId,a_resourceId);
        }
        catch(Exception ex){
            System.debug('An Exception: '+ex);
            return null;
        }
    }
 
 
    public static Date insLOG(Integer a_Time_Spent, String a_Work_Description, Date a_Date, String a_taskId, Id a_resourceId){
        try{
            Log_Table__c a_Rec = new Log_Table__c();
            a_Rec.Time_Spent__c = a_Time_Spent;
            a_Rec.Work_Description__c = a_Work_Description;
            a_Rec.Date__c = a_Date;
            a_Rec.Task__c = a_taskId;
            a_Rec.Resource__c = a_resourceId;

            Insert a_Rec;
            return a_Rec.Date__c;
        }
        catch(Exception ex){
            System.debug('An Exception: '+ex);
            return null;
        }
    }
 
    @AuraEnabled(cacheable=true)
    public static list<Log_Table__c> findLogs(string searchKey){
        System.debug('findLogs searchKey: '+searchKey);
        List<Log_Table__c> lst = new List<Log_Table__c>([SELECT Id, Name, Time_Spent__c, Work_Description__c, Date__c,Resource__r.name,ResourceName__c FROM Log_Table__c WHERE Task__c = :searchKey  ORDER BY Date__c DESC]);
        return lst;
    }    
}