force-app/main/default/objects/Contact/fields/Cadence_Meetings__c.field-meta.xml
<CustomField>
    <fullName>Cadence_Meetings__c</fullName>
    <defaultValue>&apos;None&apos;</defaultValue>
    <label>Cadence Meetings</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Priority to Setup</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Caelius_Alignment__c.field-meta.xml
<CustomField>
    <fullName>Caelius_Alignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Who at Caelius is aligned to this contact, or the primary holder of the relationship</inlineHelpText>
    <label>Caelius Alignment</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Salesforce_Industry__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Industry__c</fullName>
    <inlineHelpText>What industr</inlineHelpText>
    <label>Salesforce Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>RCG: Retail &amp; Consumer Goods</fullName>
            </value>
            <value>
                <fullName>HLS: Health, and Life Sciences</fullName>
            </value>
            <value>
                <fullName>CBS: Consumer &amp; Business Services</fullName>
            </value>
            <value>
                <fullName>CMT: Communications, Media, Technology</fullName>
            </value>
            <value>
                <fullName>TTH: Travel, Transportation, Hospitality</fullName>
            </value>
            <value>
                <fullName>FINS: Financial Services</fullName>
            </value>
            <value>
                <fullName>NPO: Non-Profit Org</fullName>
            </value>
            <value>
                <fullName>EDU: Education</fullName>
            </value>
            <value>
                <fullName>MAE: Manufacturing, Automotive, Energy</fullName>
            </value>
            <value>
                <fullName>GEOs: non-typical brands</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Salesforce_Market__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Market__c</fullName>
    <description>What market does their remit cover?</description>
    <inlineHelpText>What market does their remit cover?</inlineHelpText>
    <label>Salesforce Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
                <default>true</default>
                <label>Americas</label>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>UKI</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>Nordics</fullName>
            </value>
            <value>
                <fullName>BeNeLux</fullName>
            </value>
            <value>
                <fullName>MENA</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Salesforce_Segment__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Segment__c</fullName>
    <inlineHelpText>What segment does this contact target</inlineHelpText>
    <label>Salesforce Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Start &amp; Enterprise: Combined segment</fullName>
            </value>
            <value>
                <fullName>Strategic (STRAT): Top Accounts, highest ACV</fullName>
            </value>
            <value>
                <fullName>Enterprise: 4501+ employees</fullName>
            </value>
            <value>
                <fullName>Mid Commercial (CMRCL): 201 - 4500 employees</fullName>
            </value>
            <value>
                <fullName>Small &amp; Midsize Business Segment (SMB): &lt;200 employees</fullName>
            </value>
            <value>
                <fullName>Growth Business (GRB): 45 - 199 employees</fullName>
            </value>
            <value>
                <fullName>Small Business (SB): 0 - 45 employees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Salesforce_Technology__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Technology__c</fullName>
    <inlineHelpText>What Salesforce technology(s) does this contact service?</inlineHelpText>
    <label>Salesforce Technology</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Salesforce: All</fullName>
            </value>
            <value>
                <fullName>MuleSoft: All</fullName>
            </value>
            <value>
                <fullName>MuleSoft: Automation</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Industry</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Tableau</fullName>
            </value>
            <value>
                <fullName>Slack</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>CPQ</fullName>
            </value>
            <value>
                <fullName>DataCloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactTriggerHelper.cls
public without sharing class ContactTriggerHelper {

    public static final List<String> TRIGGER_FIELDS = new List<String>{
        'Caelius_Alignment__c',
        'Salesforce_Market__c',
        'Salesforce_Segment__c',
        'Cadence_Meetings__c',
        'Salesforce_Technology__c',
        'Salesforce_Industry__c'
    };
    public void updateChildRecords(List<Contact> newContacts, Map<Id, Contact> oldMap){
        List<Contact> consToUpdate = new List<Contact>();
        Set<Id> parentConIds = new Set<Id>();
    	Map<Id, Contact> parentConsMap = new Map<Id, Contact>();
    	Set<Id> processedIds = new Set<Id>();
    	for(Contact con : newContacts){
            Boolean isChanged = false;
        	
            for(String fieldName : TRIGGER_FIELDS){
                if ((con.get(fieldName) != NULL) && (oldMap.get(con.Id).get(fieldName) != con.get(fieldName))) {
                    isChanged = true;
                    break;
                }
            }
        	if(isChanged){
            	parentConsMap.put(con.Id, con);
                parentConIds.add(con.Id);
        	}            
    	}
    	if(!(parentConsMap.keySet().isEmpty())){
            //Set<Id> parentConIds = new Set<Id>();
            //parentConIds.addAll(parentConsMap.keySet());

        	getChildRecordsRecursively(parentConIds, processedIds, consToUpdate, parentConsMap);
    	}
    
    	if(!consToUpdate.isEmpty()){
            try{
                update consToUpdate;
            } catch(Exception e){
                String errorMessage = 'Error in ContactStatusUpdateBatch: ' + e.getMessage() + '\n' + e.getStackTraceString();
            	SendErrorEmail.sendEmail(errorMessage);
            }
    	}
    }
    public void getChildRecordsRecursively(Set<Id> parentconIds, Set<Id> processedIds, List<Contact> consToUpdate, Map<Id, Contact> parentConsMap){
        Boolean isProcessed = false;
        Set<Id> newParentIds = new Set<Id>();
        Map<Id, Contact> newParentMap = new Map<Id, Contact>();
        //using map of fields and their values instead of object 
        //Map<Id, Map<String, String

        List<Contact> conList = [SELECT Id,Name, Caelius_Alignment__c,Salesforce_Market__c,Salesforce_Segment__c,Cadence_Meetings__c, Salesforce_Technology__c, Salesforce_Industry__c, ReportsToId FROM Contact WHERE ReportsToId IN: parentconIds];
        if(conList.isEmpty()){
            return;
        }
        for(Contact con : conList){
            //test changes start
            Contact con2 = new Contact();
            con2.Id = con.Id;

            if(processedIds.contains(con.Id)){
            
                //return;
                isProcessed = true;
            }
            if(!isProcessed){
              
                Boolean isAnyFieldUpdated = false;
                for (String fieldName : TRIGGER_FIELDS) {
                    if (con.get(fieldName) == NULL) {
                        
                        System.debug('Inside child con: ' + con.Id);
                        processedIds.add(con.Id);
                        if (con.ReportsToId != NULL && parentConsMap.get(con.ReportsToId) != NULL) {
                            con.put(fieldName, parentConsMap.get(con.ReportsToId).get(fieldName));
                            //101 starts
                            con2.put(fieldName, parentConsMap.get(con.ReportsToId).get(fieldName));
                            //101 ends
                            isAnyFieldUpdated = true;
                            //test changes start 101
                            //newParentMap.put(con.Id, con);
                            //test changes end
                        }
                    } else {
                       
                        //101 con.put(fieldName, parentConsMap.get(con.ReportsToId).get(fieldName));
                        //test changes start 101
                        
                        con2.put(fieldName, parentConsMap.get(con.ReportsToId).get(fieldName));
                     
                        isAnyFieldUpdated = true;
                        //101 newParentMap.put(con.Id, con2);
                        //test changes end
                    }
                }
                if (isAnyFieldUpdated) {
                    consToUpdate.add(con);
                    newParentIds.add(con.Id);
                    newParentMap.put(con.Id, con2);
                }

            }
        }
        if (isProcessed) {
            return;
        }
        getChildRecordsRecursively(newParentIds, processedIds, consToUpdate, newParentMap);
    }
}