force-app/main/default/objects/Contact/fields/Salesforce_Relationship_Level__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Relationship_Level__c</fullName>
    <label>Salesforce Relationship Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Left Salesforce</fullName>
            </value>
            <value>
                <fullName>Unaware</fullName>
            </value>
            <value>
                <fullName>Targeted for Alignment</fullName>
            </value>
            <value>
                <fullName>First Introduction</fullName>
            </value>
            <value>
                <fullName>Aligned</fullName>
            </value>
            <value>
                <fullName>First Active Pursuit</fullName>
            </value>
            <value>
                <fullName>Closed Business</fullName>
            </value>
            <value>
                <fullName>Actively Referring</fullName>
            </value>
            <value>
                <fullName>Top Partner</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Salesforce_Contact__c/Opportunity_Salesforce_Contact__c.object-meta.xml
<CustomObject>
    <description>Salesforce team attached to this opportunity. This object is to circumvent rolling up all of the activities from the standard Opportunity Contact object</description>
    <label>Salesforce Contact</label>
    <nameField>
        <label>Opportunity Salesforce Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Salesforce_Contact__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Salesforce Contacts</relationshipLabel>
    <relationshipName>Opportunity_Salesforce_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Salesforce_Contact__c/fields/Salesforce_Contact__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Contact__c</fullName>
    <label>Salesforce Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Salesforce Contacts</relationshipLabel>
    <relationshipName>Opportunity_Salesforce_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ContactStatusUpdateBatch.cls
public class ContactStatusUpdateBatch implements Database.Batchable<sobject>, Database.Stateful, Schedulable {
    
    public Map<Id,Integer> contactUpdateMap;
    public Map<Id,String> contactStatusMap;
    public ContactStatusUpdateBatch(){
        contactUpdateMap = new Map<Id,Integer>();
        contactStatusMap = new Map<Id,String>();
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'Select Id,Salesforce_Contact__r.name,Opportunity__r.StageName,Salesforce_Contact__r.Salesforce_Relationship_Level__c,Salesforce_Contact__c  from Opportunity_Salesforce_Contact__c where Opportunity__r.StageName != \'Closed Lost\' and Salesforce_Contact__r.Salesforce_Relationship_Level__c != \'Actively Referring\'   ' ;
        
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<Opportunity_Salesforce_Contact__c> scope){
        try{
        for(Opportunity_Salesforce_Contact__c salesforceContact : scope ){
            Integer closedOppCount = contactUpdateMap.containsKey(salesforceContact.Salesforce_Contact__c) ? contactUpdateMap.get(salesforceContact.Salesforce_Contact__c) : 0;
            String contactCurrentStatus = contactStatusMap.containsKey(salesforceContact.Salesforce_Contact__c) ? contactStatusMap.get(salesforceContact.Salesforce_Contact__c) : salesforceContact.Salesforce_Contact__r.Salesforce_Relationship_Level__c;  
            if(salesforceContact.Opportunity__r.StageName == 'Closed Won'){
                  closedOppCount +=1;
            } 
            contactUpdateMap.put(salesforceContact.Salesforce_Contact__c,closedOppCount);
            contactStatusMap.put(salesforceContact.Salesforce_Contact__c,contactCurrentStatus);
        }
        } catch(Exception e){
            String errorMessage = 'Error in ContactStatusUpdateBatch: ' + e.getMessage() + '\n' + e.getStackTraceString();
            SendErrorEmail.sendEmail(errorMessage);
        }
      
    }
    
    public void finish(Database.BatchableContext bc){
        try{
        List<Contact> contactUpdateList = new List<Contact>();
        
        for(Id contactId : contactUpdateMap.keySet()){
            Integer closedOppCount = contactUpdateMap.get(contactId);
            String currentContactStatus = contactStatusMap.get(contactId);
            Contact newContact = new Contact();
            newContact.Id = contactId;
            
            if(closedOppCount == 0){
                if(currentContactStatus == '' || currentContactStatus == null ){
                    newContact.Salesforce_Relationship_Level__c = 'First Active Pursuit';
                    contactUpdateList.add(newContact);
                }
            }
            else if(closedOppCount == 1){
                if(currentContactStatus != 'Closed Business'){
                    newContact.Salesforce_Relationship_Level__c = 'Closed Business';
                    contactUpdateList.add(newContact);
                }
            }
            else if(closedOppCount > 1){
                
                newContact.Salesforce_Relationship_Level__c = 'Actively Referring';
                contactUpdateList.add(newContact);
                
            }
        }
        
        if(contactUpdateList.Size() > 0){
            update contactUpdateList;
        }
        } catch(Exception e){
            String errorMessage = 'Error in ContactStatusUpdateBatch: ' + e.getMessage() + '\n' + e.getStackTraceString();
            SendErrorEmail.sendEmail(errorMessage);
        }
            
    }
    
    public void execute(SchedulableContext SC){
        database.executeBatch(new ContactStatusUpdateBatch());
    }
}