force-app/main/default/objects/FPSA_Project_Allocation__c/FPSA_Project_Allocation__c.object-meta.xml
<CustomObject>
    <label>Project Allocation</label>
    <nameField>
        <label>Allocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FPSA_Project_Allocation__c/fields/FPSA_Resource__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reparenting is allowed because we set the Master object through code otherwise code throws error &quot;Field is not writable&quot;</description>
    <label>Resource</label>
    <referenceTo>MPM4_BASE__Milestone1_Resource__c</referenceTo>
    <relationshipLabel>Project Allocations</relationshipLabel>
    <relationshipName>Project_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FPSA_Project_Allocation__c/fields/FPSA_Status__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPSA_Project_Allocation__c/fields/FPSA_Week_1_hrs__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Week_1_hrs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Week 1</label>
    <precision>7</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FPSA_Project_Allocation__c/fields/FPSA_Week_2_hrs__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Week_2_hrs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Week 2</label>
    <precision>7</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FPSA_Resource_TimeLines__c/FPSA_Resource_TimeLines__c.object-meta.xml
<CustomObject>
    <label>Resource TimeLine</label>
    <nameField>
        <displayFormat>TL-{00000}</displayFormat>
        <label>Timecard Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource TimeLines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FPSA_Resource_TimeLines__c/fields/FPSA_Approver__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Based on the Project Approver Field</inlineHelpText>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resource_TimeLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FPSA_Resource_TimeLines__c/fields/FPSA_Resource__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reparenting is allowed because we set the Master object through code otherwise code throws error &quot;Field is not writable&quot;</description>
    <label>Resource</label>
    <referenceTo>MPM4_BASE__Milestone1_Resource__c</referenceTo>
    <relationshipLabel>Resource TimeLines</relationshipLabel>
    <relationshipName>Resource_TimeLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FPSA_Resource_TimeLines__c/fields/FPSA_Status__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPM4_BASE__Milestone1_Project__c/MPM4_BASE__Milestone1_Project__c.object-meta.xml
<CustomObject>
    <description>Passage Technology - Milestones PM+ Free Edition - A project can have many milestones.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPM4_BASE__Milestone1_Project__c/fields/FPSA_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Start_Date__c</fullName>
    <inlineHelpText>Enter the Date the project is going to start. Allocation changes automatically with change in start date. Start date cannot be changed once even one timecard is submitted for the project</inlineHelpText>
    <label>Start Date as per SoW</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MPM4_BASE__Milestone1_Resource__c/MPM4_BASE__Milestone1_Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/MPM4_BASE__Milestone1_Resource__c/fields/FPSA_Start_date__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Start_date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/FPSA_CTRL_TimecardPendingApprovalsTest.cls
@isTest
private class FPSA_CTRL_TimecardPendingApprovalsTest {

    private static final String TIMECARD_STATUS_SUBMITTED = Label.FPSA_Timecard_Status_Submitted;
/*    
    @TestSetup
    private static void setupTestData() {
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];

        User testUser = new User(Alias = 'standt', Email = 'testUser9118@xyz.com', EmailEncodingKey = 'UTF-8', LastName = 'Testing', 
                                 LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = adminProfile.Id, 
                                 TimeZoneSidKey = 'America/Los_Angeles', UserName = 'testUser9118@xyz.com');
        insert testUser;

        Account accountRecord = FPSA_TestDataFactory.createAccount();
        User userRecord = new user(Id = UserInfo.getUserId());
        MPM4_BASE__Milestone1_Resource__c resourceRecord = FPSA_TestDataFactory.createResource(testUser.Id);
        MPM4_BASE__Milestone1_Project__c projectRecord = FPSA_TestDataFactory.createProject(accountRecord.Id, System.today(), 30, testUser.Id);

        FPSA_ResourceAllocation.InnerWrapper innerwrap = new FPSA_ResourceAllocation.InnerWrapper();
        innerwrap.key ='FPSA_Week_1_hrs__c';
        innerwrap.value = 40;
        
        FPSA_ResourceAllocation.InnerWrapper innerwrap2 = new FPSA_ResourceAllocation.InnerWrapper();
        innerwrap2.key ='FPSA_Week_2_hrs__c';
        innerwrap2.value = 40;

        FPSA_ResourceAllocation.OuterWrapper outwrap = new FPSA_ResourceAllocation.OuterWrapper();
        outwrap.projAlloc = new FPSA_Project_Allocation__c(FPSA_Resource__c = resourceRecord.Id);
        outwrap.projAllocationHours= new List<FPSA_ResourceAllocation.InnerWrapper>{innerwrap, innerwrap2};

        FPSA_ResourceAllocation.WrapperResponse  wrap = new FPSA_ResourceAllocation.WrapperResponse();
        wrap.weekStarting =  new List<Date>{system.today()};           
        wrap.loggedInUserProfile =true;
        wrap.roleValues =new List<String>{'Developer', 'QA'};
        wrap.duration = 10;
        wrap.projRec = projectRecord;
        wrap.projAllocationRec = new List<FPSA_ResourceAllocation.OuterWrapper> {outwrap};

        FPSA_ResourceAllocation.saveAllocations(wrap);
        FPSA_ResourceAllocation.getResourceAllocation(projectRecord.Id);

        MPM4_BASE__Milestone1_Project__c projectInst = new MPM4_BASE__Milestone1_Project__c(Id = projectRecord.Id, FPSA_Start_Date__c = System.today().addDays(8));
        Database.update(projectInst,false);
    }
*/
/*
    @isTest
    private static void testGetPendingTimecardApprovalRequests() {
        List<FPSA_Resource_TimeLines__c> timesheets = [SELECT Id, FPSA_Status__c, FPSA_Approver__c FROM FPSA_Resource_TimeLines__c ];
        
        for(FPSA_Resource_TimeLines__c timesheet : timesheets) {
            timesheet.FPSA_Approver__c = UserInfo.getUserId();
            timesheet.FPSA_Status__c = TIMECARD_STATUS_SUBMITTED;
        }

        update timesheets;

        Test.startTest();
        List<FPSA_Resource_TimeLines__c> timecardEntries = FPSA_CTRL_TimecardPendingApprovals.getPendingTimecardApprovalRequests();
        Test.stopTest();

        System.assertEquals(timesheets.size(), timecardEntries.size());
    }

    @isTest (SeeAllData=true)
    private static void testProcessTimecardApprovalRequests() {
        List<FPSA_Resource_TimeLines__c> timesheets = [SELECT Id, FPSA_Status__c, FPSA_Approver__c FROM FPSA_Resource_TimeLines__c];
        List<String> timecardIds = new List<String> {timesheets[0].Id, timesheets[1].Id};

        Test.startTest();
        FPSA_CTRL_TimecardPendingApprovals.processTimecardApprovalRequests(timecardIds, 'Approve');
        Test.stopTest();
    }*/
}