force-app/main/default/objects/FPSA_Project_Allocation__c/FPSA_Project_Allocation__c.object-meta.xml
<CustomObject>
    <label>Project Allocation</label>
    <nameField>
        <label>Allocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FPSA_Project_Allocation__c/fields/FPSA_Week_1_hrs__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Week_1_hrs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Week 1</label>
    <precision>7</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FPSA_Project_Allocation__c/fields/Resource_Name__c.field-meta.xml
<CustomField>
    <fullName>Resource_Name__c</fullName>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.Account_Name__c</field>
            <operation>equals</operation>
            <value>Caelius Consulting</value>
        </filterItems>
        <filterItems>
            <field>Contact.Account_Name__c</field>
            <operation>equals</operation>
            <value>Test Cls Acct</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Project Allocations</relationshipLabel>
    <relationshipName>Project_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MPM4_BASE__Milestone1_Project__c/MPM4_BASE__Milestone1_Project__c.object-meta.xml
<CustomObject>
    <description>Passage Technology - Milestones PM+ Free Edition - A project can have many milestones.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPM4_BASE__Milestone1_Resource__c/MPM4_BASE__Milestone1_Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/FPSA_TestResourceAllocation.cls
@isTest
public class FPSA_TestResourceAllocation {
    static testMethod void test_resourceAllocation(){
        test.starttest();
            Account accountRecord = FPSA_TestDataFactory.createAccount();//Create Account
            User userRecord = new user(id=userinfo.getuserid());//Create User
            MPM4_BASE__Milestone1_Resource__c resourceRecord = FPSA_TestDataFactory.createResource(userRecord.Id);//Create Resource        
            MPM4_BASE__Milestone1_Project__c projectRecord = FPSA_TestDataFactory.createProject(accountRecord.Id,System.today(),30,userRecord.Id);//Create Project  
            Account acct = new Account(Name = 'Test Cls Acct');
            insert acct;   
            Contact conRecord = FPSA_TestDataFactory.createContact(acct.id, 'Test', 'Contact', TRUE);   
            
          //Call the fetchAccount method
          lookUpController.fetchAccount('Res');
          
          //Call the GetRecentRecords method
          lookupfieldController.GetRecentRecords('MPM4_BASE__Milestone1_Resource__c', null, 1);
        
          //Call the SearchRecords method
          lookupfieldController.SearchRecords('MPM4_BASE__Milestone1_Resource__c', null, null, 'Res', null, null, 1, null);  
        
          //Call the GetRecord method
          lookupfieldController.GetRecord('MPM4_BASE__Milestone1_Resource__c',null,(String)resourceRecord.Id);
        
          //Call the findObjectIcon method
          lookupfieldController.findObjectIcon('MPM4_BASE__Milestone1_Resource__c');
        
          //Call the getObjectDetails method
          lookupfieldController.getObjectDetails('MPM4_BASE__Milestone1_Resource__c');
                
            //Create Resource Allocation wrapper
            FPSA_ResourceAllocation.WrapperResponse  wrap = new FPSA_ResourceAllocation.WrapperResponse();
                wrap.weekStarting =  new List<Date>{system.today()};
                wrap.loggedInUserProfile = true;
                wrap.roleValues =new List<String>{'Developer', 'QA'};
                wrap.duration =10;
                wrap.projRec =projectRecord;
                FPSA_ResourceAllocation.OuterWrapper outwrap = new FPSA_ResourceAllocation.OuterWrapper();
                FPSA_ResourceAllocation.InnerWrapper innerwrap = new FPSA_ResourceAllocation.InnerWrapper();
                    innerwrap.key ='FPSA_Week_1_hrs__c';
                    innerwrap.value=40;
                    outwrap.projAlloc = new FPSA_Project_Allocation__c(Resource_Name__c=conRecord.id);
                    outwrap.projAllocationHours= new list<FPSA_ResourceAllocation.InnerWrapper>{innerwrap};        
                wrap.projAllocationRec = new list<FPSA_ResourceAllocation.OuterWrapper>{outwrap};
            
            //Call the saveAllocations method
            FPSA_ResourceAllocation.saveAllocations(wrap);
            
            //Call the getResourceAllocation method
            FPSA_ResourceAllocation.getResourceAllocation(projectRecord.Id);
            
            //Call the deleteAllocations method
            FPSA_ResourceAllocation.deleteAllocations((String)[Select id from FPSA_Project_Allocation__c LIMIT 1][0].Id);

            FPSA_ResourceAllocation.fetchAllocationWrapper(projectRecord.Id);

            FPSA_ResourceAllocation.getResourceAllocation(projectRecord.Id);

            FPSA_ResourceAllocation.getFieldSetMetadata('FPSA_Project_Allocation__c', 'Allocation_Fields');

            FPSA_ResourceAllocation.fetchResourceAllocations(projectRecord.Id, '809090909');
        test.stopTest();
    }
}