force-app/main/default/objects/FPSA_Resource_TimeLines__c/FPSA_Resource_TimeLines__c.object-meta.xml
<CustomObject>
    <label>Resource TimeLine</label>
    <nameField>
        <displayFormat>TL-{00000}</displayFormat>
        <label>Timecard Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource TimeLines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FPSA_Resource_TimeLines__c/fields/FPSA_Approver__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Based on the Project Approver Field</inlineHelpText>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resource_TimeLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FPSA_Resource_TimeLines__c/fields/FPSA_Milestone__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Milestone</label>
    <referenceTo>MPM4_BASE__Milestone1_Milestone__c</referenceTo>
    <relationshipLabel>Resource TimeLines</relationshipLabel>
    <relationshipName>Resource_TimeLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FPSA_Resource_TimeLines__c/fields/FPSA_Project__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>MPM4_BASE__Milestone1_Project__c</referenceTo>
    <relationshipLabel>Resource TimeLines</relationshipLabel>
    <relationshipName>Resource_TimeLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FPSA_Resource_TimeLines__c/fields/FPSA_Project_Planned_hrs__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Project_Planned_hrs__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>This is the planned efforts of the resource.</inlineHelpText>
    <label>Project Planned Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FPSA_Resource_TimeLines__c/fields/FPSA_Resource__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reparenting is allowed because we set the Master object through code otherwise code throws error &quot;Field is not writable&quot;</description>
    <label>Resource</label>
    <referenceTo>MPM4_BASE__Milestone1_Resource__c</referenceTo>
    <relationshipLabel>Resource TimeLines</relationshipLabel>
    <relationshipName>Resource_TimeLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FPSA_Resource_TimeLines__c/fields/FPSA_Status__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPSA_Resource_TimeLines__c/fields/FPSA_Total_Billable_Amount__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Total_Billable_Amount__c</fullName>
    <formula>FPSA_BillRate__c *  FPSA_Total_Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Billable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FPSA_Resource_TimeLines__c/fields/FPSA_Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Total_Hours__c</fullName>
    <formula>FPSA_Sunday_Hours__c + FPSA_Tuesday_Hours__c +  FPSA_Monday_Hours__c  +  FPSA_Wednesday_Hours__c + FPSA_Thursday_Hours__c + FPSA_Saturday_Hours__c + FPSA_Friday_Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FPSA_Resource_TimeLines__c/fields/FPSA_Week_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Week_Start_Date__c</fullName>
    <label>Week Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FPSA_Resource_TimeLines__c/fields/FPSA_Weekly_Notes__c.field-meta.xml
<CustomField>
    <fullName>FPSA_Weekly_Notes__c</fullName>
    <label>Weekly Notes</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPM4_BASE__Milestone1_Milestone__c/MPM4_BASE__Milestone1_Milestone__c.object-meta.xml
<CustomObject>
    <description>Passage Technology - Milestones PM+ Free Edition - Milestones are significant events in the life-cycle of a Project. You can also use them to track project phases. Milestones can have tasks and sub-milestones associated with them.</description>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPM4_BASE__Milestone1_Project__c/MPM4_BASE__Milestone1_Project__c.object-meta.xml
<CustomObject>
    <description>Passage Technology - Milestones PM+ Free Edition - A project can have many milestones.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPM4_BASE__Milestone1_Resource__c/MPM4_BASE__Milestone1_Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/FPSA_TimecardPendingApprovalsHelper.cls
public class FPSA_TimecardPendingApprovalsHelper {

    /*private static final String TIMECARD_STATUS_SUBMITTED = Label.FPSA_Timecard_Status_Submitted;

    public static List<FPSA_Resource_TimeLines__c> getSubmittedTimecardLines() {
        Id approverId = UserInfo.getUserId();

        return [SELECT Id, Name, FPSA_Week_Start_Date__c, FPSA_Total_Hours__c, FPSA_Project_Planned_hrs__c, FPSA_Total_Billable_Amount__c,
                FPSA_Weekly_Notes__c, FPSA_Resource__c, FPSA_Resource__r.Name, FPSA_Project__c, FPSA_Project__r.Name, 
                FPSA_Milestone__c, FPSA_Milestone__r.Name
                FROM FPSA_Resource_TimeLines__c
                WHERE FPSA_Approver__c = :approverId AND
                FPSA_Status__c = :TIMECARD_STATUS_SUBMITTED];
    }

    public static List<Id> getTypecastTimecardIds(List<String> timecardIds) {
        List<Id> timecardIdList = new List<Id>();

        for(String timecardId : timecardIds) {
            timecardIdList.add(Id.valueOf(timecardId));
        }

        return timecardIdList;
    }

    public static List<Approval.ProcessWorkItemRequest> getProcessWorkItemRequests(List<Id> timecardIds, String approvalAction) {
        Map<Id, Id> timecardIdToWorkItemIdMap = getTimecardIdToWorkItemIdMap(timecardIds);

        List<Approval.ProcessWorkItemRequest> workItemRequests = new List<Approval.ProcessWorkItemRequest>();

        for(Id timecardId : timecardIds) {
            Approval.ProcessWorkItemRequest workItemRequest = new Approval.ProcessWorkItemRequest();
            workItemRequest.setAction(approvalAction);
            workItemRequest.setWorkitemId(timecardIdToWorkItemIdMap.get(timecardId));
            workItemRequests.add(workItemRequest);
        }

        return workItemRequests;
    }

    private static Map<Id, Id> getTimecardIdToWorkItemIdMap(List<Id> timecardIds) {
        Map<Id, Id> timecardIdToWorkItemIdMap = new Map<Id, Id>();
        List<ProcessInstanceWorkItem> workItems = [SELECT Id, ProcessInstance.TargetObjectId 
                                                   FROM ProcessInstanceWorkItem 
                                                   WHERE ProcessInstance.TargetObjectId IN :timecardIds];
        
        for(ProcessInstanceWorkItem workItem : workItems) {
            timecardIdToWorkItemIdMap.put(workItem.ProcessInstance.TargetObjectId, workItem.Id);
        }

        return timecardIdToWorkItemIdMap;
    }

    public static Boolean isApprovalRequestProcessed(List<Approval.ProcessResult> approvalResults) {
        Boolean isProcessed = true;

        for(Approval.ProcessResult approvalResult : approvalResults) {
            if(!approvalResult.isSuccess()) {
                isProcessed = false;
            }
        }

        return isProcessed;
    }*/
}